server.port=8082

spring.application.admin.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_review_data
spring.datasource.username=dev_user
spring.datasource.password=example
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
