spring:
    application:
        name: mdb-aggregator

kafka:
    host: ${kafka.host.override:localhost:9092}

postgres:
    host: ${postgres.host.override:localhost:5432}

server:
    servlet:
        context-path: /api
