server.port=8084

#spring.r2dbc.url=r2dbc:postgresql://localhost:5432/read_db
#spring.r2dbc.username=query_service_user
#spring.r2dbc.password=jw8s0F4

spring.sql.init.mode=always

spring.kafka.listener.poll-timeout=3000
spring.kafka.listener.concurrency=1
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE

spring.kafka.consumer.bootstrap.servers=${kafka.host}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.properties.isolation.level=read_committed
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

query.service.kafka.in.review-events-topic=movie-review-events
query.service.kafka.in.user-events-topic=user-events
query.service.kafka.in.movie-events-topic=movie-events

logging.level.org.springframework.r2dbc=DEBUG
