server.port=8084

spring.r2dbc.url=r2dbc:postgresql://${postgres.host}/read_db
spring.r2dbc.username=query_service_user
spring.r2dbc.password=jw8s0F4
spring.sql.init.mode=always
spring.data.r2dbc.repositories.enabled-=false

spring.kafka.listener.poll-timeout=3000
spring.kafka.listener.concurrency=1
spring.kafka.listener.ack-mode=MANUAL_IMMEDIATE

spring.kafka.bootstrap-servers=${kafka.host}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.properties.isolation.level=read_committed
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=java.lang.Object
spring.kafka.consumer.properties.spring.json.trusted.packages=me.mzalietin.mdbproject.query.broker.event,java.lang
spring.kafka.consumer.properties.spring.json.type.mapping=\
  movie_created:me.mzalietin.mdbproject.queryservice.domain.model.event.MovieCreated,\
  movie_rating_updated:me.mzalietin.mdbproject.queryservice.domain.model.event.MovieRatingUpdated,\
  review_created:me.mzalietin.mdbproject.queryservice.domain.model.event.ReviewCreated,\
  review_updated:me.mzalietin.mdbproject.queryservice.domain.model.event.ReviewUpdated,\
  review_deleted:me.mzalietin.mdbproject.queryservice.domain.model.event.ReviewDeleted,\
  review_key:me.mzalietin.mdbproject.queryservice.domain.model.event.ReviewKey,\
  user_created:me.mzalietin.mdbproject.queryservice.domain.model.event.UserCreated

query.service.kafka.in.review-events-topic=movie-review-events
query.service.kafka.in.user-events-topic=user-events
query.service.kafka.in.movie-events-topic=movie-events

logging.level.org.springframework.r2dbc=DEBUG
